SWITCH_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD_C += $(SWITCH_MOD_DIR)/modswitch.c
SRC_USERMOD_C += $(SWITCH_MOD_DIR)/modusb.c
SRC_USERMOD_C += $(SWITCH_MOD_DIR)/modgfx.c
SRC_USERMOD_C += $(SWITCH_MOD_DIR)/modnxapp.c
SRC_USERMOD_C += $(SWITCH_MOD_DIR)/modhttp.c
CFLAGS_USERMOD += -I$(SWITCH_MOD_DIR)
