#!/usr/bin/env python3
"""Generates modules/switch/gfx_font.h (8x16 bitmap font for the gfx module)
from the OpenType version of GNU Unifont.

Requirements: Pillow (pip install pillow) and unifont.otf
(Debian/Ubuntu: apt install fonts-unifont; or download from https://unifoundry.com).

Usage:
    python3 tools/make_font.py [path/to/unifont.otf]
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "modules" / "switch" / "gfx_font.h"
DEFAULT_FONT = "/usr/share/fonts/opentype/unifont/unifont.otf"

# Character ranges to include (only glyphs that are 8 pixels wide are kept)
RANGES = [
    (0x0020, 0x007E),   # ASCII
    (0x00A0, 0x00FF),   # Latin-1 supplement
    (0x0400, 0x045F),   # Cyrillic
    (0x2010, 0x2027),   # dashes, quotes, bullet, ellipsis
    (0x2190, 0x2195),   # arrows
    (0x2212, 0x2212),   # minus sign
    (0x2500, 0x259F),   # box drawing and block elements
    (0x25A0, 0x25CF),   # geometric shapes
]


def render(font, ch):
    """Returns a 16x16 1-bit image of the glyph (wide enough to detect wide glyphs)."""
    im = Image.new("1", (16, 16), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((0, 0), ch, font=font, fill=1)
    return im


def main():
    font_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    font = ImageFont.truetype(font_path, 16)

    codes, bitmaps = [], []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            if font.getlength(ch) != 8:          # skip double-width and missing glyphs
                continue
            im = render(font, ch)
            if any(im.getpixel((x, y)) for x in range(8, 16) for y in range(16)):
                continue
            rows = []
            for y in range(16):
                bits = 0
                for x in range(8):
                    if im.getpixel((x, y)):
                        bits |= 0x80 >> x
                rows.append(bits)
            if cp != 0x20 and cp != 0xA0 and not any(rows):
                continue                          # empty glyph that should not be empty
            codes.append(cp)
            bitmaps.append(rows)

    lines = [
        "// 8x16 bitmap font for the gfx module. GENERATED by tools/make_font.py, do not edit.",
        "//",
        "// Glyphs from GNU Unifont 15.1.01:",
        "// Copyright (C) 1998-2023 Roman Czyborra, Paul Hardy, Qianqian Fang, Andrew Miller,",
        "// Johnnie Weaver, David Corbett, Nils Moskopp, Rebecca Bettencourt, Minseo Lee,",
        "// Ho-Seok Ee, et al.",
        "// Dual license: SIL Open Font License version 1.1, and GNU GPL version 2 or later",
        "// with the GNU Font Embedding Exception. See licenses/UNIFONT.txt.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define GFX_FONT_W      8",
        "#define GFX_FONT_H      16",
        f"#define GFX_FONT_COUNT  {len(codes)}",
        "",
        "// Sorted code points (binary search) and 16 rows per glyph, MSB = leftmost pixel",
        "static const uint16_t gfx_font_codes[GFX_FONT_COUNT] = {",
    ]
    for i in range(0, len(codes), 12):
        lines.append("    " + ", ".join("0x%04X" % c for c in codes[i:i + 12]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("static const uint8_t gfx_font_bitmaps[GFX_FONT_COUNT][GFX_FONT_H] = {")
    for cp, rows in zip(codes, bitmaps):
        lines.append("    {" + ",".join("0x%02X" % r for r in rows) + "},  // U+%04X" % cp)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT} ({len(codes)} glyphs)")


if __name__ == "__main__":
    main()
